// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (

	"github/faith2333/xuanwu/internal/conf"
	"github/faith2333/xuanwu/internal/server"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	//dataData, cleanup, err := data.NewData(confData, logger)
	//if err != nil {
	//	return nil, nil, err
	//}
	grpcServer := server.NewGRPCServer(confServer, logger)
	httpServer := server.NewHTTPServer(confServer, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		//cleanup()
	}, nil
}
