// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github/faith2333/xuanwu/internal/conf"
	"github/faith2333/xuanwu/internal/server"
	"github/faith2333/xuanwu/internal/service/cicd"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	cicdService := service.NewCICDService()
	grpcServer := server.NewGRPCServer(confServer, cicdService, logger)
	httpServer := server.NewHTTPServer(confServer, cicdService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
