package cicd

import (
	"context"
	"github.com/faith2333/xuanwu/internal/biz/cicd"
	"github.com/faith2333/xuanwu/internal/data/base"
)

type Template struct {
	base.ModelBase
	Name   string `json:"name" gorm:"type:varchar(64);comment:'name of cicd template,specified by create user or modify user'"`
	Code   string `json:"code" gorm:"type:varchar(64);comment:'code of cicd template,generated by system'"`
	Source string `json:"source" gorm:"type:text(20000);comment:'source yaml of template'"`
}

type TemplateRepo struct {
	base.RepoBase
	data *base.Data
}

func (tRepo *TemplateRepo) CreateTemplate(ctx context.Context, bizTemplate *cicd.CreateTemplate) (*cicd.Template, error) {
	tDB := &Template{}
	err := tRepo.Transform(bizTemplate, &tDB)
	if err != nil {
		return nil, err
	}

	err = tRepo.data.DB(ctx).Create(&tDB).Error
	if err != nil {
		return nil, err
	}

	result := &cicd.Template{}
	err = tRepo.Transform(tDB, &result)
	if err != nil {
		return nil, err
	}
	return result, nil
}
