package cicd

import (
	"github/faith2333/xuanwu/internal/biz/cicd"
	"github/faith2333/xuanwu/internal/data/base"
)

type Template struct {
	base.Base
	Name   string `json:"name" gorm:"type:varchar(64);comment:'name of cicd template,specified by create user or modify user'"`
	Code   string `json:"code" gorm:"type:varchar(64);comment:'code of cicd template,generated by system'"`
	Source string `json:"source" gorm:"type:text(20000);comment:'source yaml of template'"`
}

type TemplateRepo struct {
	data *base.Data
}

func (tRepo *TemplateRepo) CreateTemplate(request *cicd.CreateTemplate) (cicd.Template, error) {

}
