// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.12
// source: cicd/v1/cicd.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCICDCreateTemplate = "/api.cicd.v1.CICD/CreateTemplate"

type CICDHTTPServer interface {
	// CreateTemplate Template service for CICD
	CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateReply, error)
}

func RegisterCICDHTTPServer(s *http.Server, srv CICDHTTPServer) {
	r := s.Route("/")
	r.POST("/cicd/template/create", _CICD_CreateTemplate0_HTTP_Handler(srv))
}

func _CICD_CreateTemplate0_HTTP_Handler(srv CICDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTemplateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCICDCreateTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTemplate(ctx, req.(*CreateTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTemplateReply)
		return ctx.Result(200, reply)
	}
}

type CICDHTTPClient interface {
	CreateTemplate(ctx context.Context, req *CreateTemplateRequest, opts ...http.CallOption) (rsp *CreateTemplateReply, err error)
}

type CICDHTTPClientImpl struct {
	cc *http.Client
}

func NewCICDHTTPClient(client *http.Client) CICDHTTPClient {
	return &CICDHTTPClientImpl{client}
}

func (c *CICDHTTPClientImpl) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...http.CallOption) (*CreateTemplateReply, error) {
	var out CreateTemplateReply
	pattern := "/cicd/template/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCICDCreateTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
