// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: cicd/v1/cicd.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CICDClient is the client API for CICD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CICDClient interface {
	// Template service for CICD
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateReply, error)
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateReply, error)
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateReply, error)
	GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*GetTemplateReply, error)
	ListTemplate(ctx context.Context, in *ListTemplateRequest, opts ...grpc.CallOption) (*ListTemplateReply, error)
}

type cICDClient struct {
	cc grpc.ClientConnInterface
}

func NewCICDClient(cc grpc.ClientConnInterface) CICDClient {
	return &cICDClient{cc}
}

func (c *cICDClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateReply, error) {
	out := new(CreateTemplateReply)
	err := c.cc.Invoke(ctx, "/api.cicd.v1.CICD/CreateTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateReply, error) {
	out := new(UpdateTemplateReply)
	err := c.cc.Invoke(ctx, "/api.cicd.v1.CICD/UpdateTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateReply, error) {
	out := new(DeleteTemplateReply)
	err := c.cc.Invoke(ctx, "/api.cicd.v1.CICD/DeleteTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDClient) GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*GetTemplateReply, error) {
	out := new(GetTemplateReply)
	err := c.cc.Invoke(ctx, "/api.cicd.v1.CICD/GetTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDClient) ListTemplate(ctx context.Context, in *ListTemplateRequest, opts ...grpc.CallOption) (*ListTemplateReply, error) {
	out := new(ListTemplateReply)
	err := c.cc.Invoke(ctx, "/api.cicd.v1.CICD/ListTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CICDServer is the server API for CICD service.
// All implementations must embed UnimplementedCICDServer
// for forward compatibility
type CICDServer interface {
	// Template service for CICD
	CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateReply, error)
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*UpdateTemplateReply, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateReply, error)
	GetTemplate(context.Context, *GetTemplateRequest) (*GetTemplateReply, error)
	ListTemplate(context.Context, *ListTemplateRequest) (*ListTemplateReply, error)
	mustEmbedUnimplementedCICDServer()
}

// UnimplementedCICDServer must be embedded to have forward compatible implementations.
type UnimplementedCICDServer struct {
}

func (UnimplementedCICDServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedCICDServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*UpdateTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedCICDServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedCICDServer) GetTemplate(context.Context, *GetTemplateRequest) (*GetTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedCICDServer) ListTemplate(context.Context, *ListTemplateRequest) (*ListTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplate not implemented")
}
func (UnimplementedCICDServer) mustEmbedUnimplementedCICDServer() {}

// UnsafeCICDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CICDServer will
// result in compilation errors.
type UnsafeCICDServer interface {
	mustEmbedUnimplementedCICDServer()
}

func RegisterCICDServer(s grpc.ServiceRegistrar, srv CICDServer) {
	s.RegisterService(&CICD_ServiceDesc, srv)
}

func _CICD_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.cicd.v1.CICD/CreateTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICD_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.cicd.v1.CICD/UpdateTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICD_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.cicd.v1.CICD/DeleteTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICD_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.cicd.v1.CICD/GetTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServer).GetTemplate(ctx, req.(*GetTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICD_ListTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServer).ListTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.cicd.v1.CICD/ListTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServer).ListTemplate(ctx, req.(*ListTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CICD_ServiceDesc is the grpc.ServiceDesc for CICD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CICD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.cicd.v1.CICD",
	HandlerType: (*CICDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _CICD_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _CICD_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _CICD_DeleteTemplate_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _CICD_GetTemplate_Handler,
		},
		{
			MethodName: "ListTemplate",
			Handler:    _CICD_ListTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cicd/v1/cicd.proto",
}
